# Generated by Django 4.2.14 on 2025-05-27 00:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="productmodel",
            name="category",
            field=models.CharField(default="test", max_length=64),
            preserve_default=False,
        ),
    ]
