# Generated by Django 4.2.14 on 2025-08-12 17:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelTable(
            name="productmodel",
            table="products",
        ),
    ]
