# Generated by Django 4.2.14 on 2025-08-05 22:53

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="AddressModel",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("street", models.CharField(max_length=150)),
                ("street_number", models.CharField(max_length=20)),
                ("complement", models.CharField(max_length=20)),
                ("district", models.CharField(max_length=128)),
                ("city", models.CharField(max_length=255)),
                ("state_code", models.CharField(max_length=3)),
                ("postal_code", models.CharField(max_length=10)),
                ("country", models.CharField(max_length=2)),
                ("is_default", models.BooleanField(default=False)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="address",
                        to="users.usermodel",
                    ),
                ),
            ],
        ),
    ]
