# Generated by Django 4.2.14 on 2025-08-19 23:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
        ("addresses", "0002_alter_addressmodel_table"),
    ]

    operations = [
        migrations.AlterField(
            model_name="addressmodel",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="addresses",
                to="users.usermodel",
            ),
        ),
    ]
